site_name: OmniPackage documentation
site_url: "https://docs.omnipackage.org"
repo_url: "https://github.com/omnipackage/omnipackage-docs"
site_description: "Documentation for OmniPackage - Linux packaging made easy"
site_author: "Oleg Antonyan"

nav:
  - Home: index.md
  - 'Getting started': getting_started.md
  - Guides:
    - 'How it works': guides/how_it_works.md
    - 'Signing packages': guides/signing.md
    - 'Publishing to S3': guides/s3_repository.md
    - Templates: guides/templates.md
    - 'CI/CD integration': guides/cicd.md
  - Configuration:
    - Overview: configuration/index.md
    - builds: configuration/builds.md
    - version_extractors: configuration/version_extractors.md
    - repositories: configuration/repositories.md
    - image_caches: configuration/image_caches.md
    - secrets: configuration/secrets.md
  - 'CLI reference':
    - Overview: cli/index.md
    - build: cli/build.md
    - publish: cli/publish.md
    - release: cli/release.md
    - info: cli/info.md
    - gpg: cli/gpg.md
    - portal: cli/portal.md
    - prime: cli/prime.md
  - 'Supported distros': distros.md
  - Examples: examples.md

extra:
  agent_github_url: https://github.com/omnipackage/omnipackage-rs/
  examples_github_url: https://github.com/omnipackage/examples
  agent_public_install_url: https://repositories.omnipackage.org/omnipackage-rs/stable/install.html



theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.png
  font: false
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default # (1)!
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: white
      accent: custom

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
      primary: black
      accent: custom

  features:
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tracking
    - navigation.sections


plugins:
- social
- search
- privacy
- git-revision-date-localized
- macros


extra_css:
- stylesheets/extra.css


markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
