site_name: OmniPackage documentation
site_url: "https://docs.omnipackage.org"
repo_url: "https://github.com/omnipackage/omnipackage-docs"
site_description: "Documentation for OmniPackage - Linux packaging made easy"
site_author: "Oleg Antonyan"
#copyright: "Oleg Antonian PE"

nav:
  - Home: index.md
  - 'Getting started': getting_started.md
  - 'Self-hosting': self_hosting.md
  - About: about.md

extra:
  web_github_url: https://github.com/omnipackage/omnipackage-web
  agent_github_url: https://github.com/omnipackage/omnipackage-agent-ruby
  web_hosted_url: https://web.omnipackage.org
  examples_github_url: https://github.com/omnipackage/examples
  agent_public_install_url: https://web.omnipackage.org/oleg/omnipackage-agent



theme:
  name: material
  favicon: img/favicon.ico
  logo: img/logo.png
  font: false
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default # (1)!
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
      primary: white
      accent: custom

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to system preference
      primary: black
      accent: custom

  features:
    - content.code.copy
    - content.code.annotate
    - search.suggest
    - search.highlight
    - search.share
    - navigation.tracking
    - navigation.sections


plugins:
- social
- search
- privacy
- git-revision-date-localized
- macros


extra_css:
- stylesheets/extra.css


markdown_extensions:
  - abbr
  - admonition
  - footnotes
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
      use_pygments: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.details
